### ISSUE TITLE
trend-display is corrupting stack after about a day

### ISSUE THREAD

**Issue by LionsPhil** [LionsPhil/prometheus-enviro-sensors#1]
```
free(): invalid pointer

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0xb6d04230 in __GI_abort () at abort.c:79
#2  0xb6d5451c in __libc_message (action=action@entry=do_abort, fmt=<optimized out>) at ../sysdeps/posix/libc_fatal.c:181
#3  0xb6d5b044 in malloc_printerr (str=<optimized out>) at malloc.c:5341
#4  0xb6d5cd50 in _int_free (av=0xb6e377d4 <main_arena>, p=0x43417c, have_lock=<optimized out>) at malloc.c:4165
#5  0x001b6e18 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

I assume this has gotta be an upstream module bug for one using native code, e.g. the GPIO one or something. Doesn't seem to be anything as "simple" as leaking memory/address space until malloc() gives out a NULL (and that shouldn't corrupt the stack). Unfortunately the stack corruption makes identifying what, exactly, tricky.

**Comment by LionsPhil** [comment]
This seems to have calmed down after system updates, so possibly was indeed a now-fixed upstream bug.

**Comment by LionsPhil** [comment]
Yep, this fixed itself. Assuming upstream.
